# traefik-middlewares.yaml

# Traefik BasicAuth Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-basicauth
spec:
  basicAuth:
    secret: basicauth-traefik-secret
    removeHeader: false

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-basicauth
data:
  users:
    ZGV2dXNlcnRyYWVmaWs6cGFzc3dvcmRfYmFzaWNhdXRoXzY0OA==

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-whitelist
spec:
  ipWhiteList:
    sourceRange:
      - 20.74.96.2